name: Blood pressure build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
      - uses: actions/checkout@v4
        with:
          first_name: Adithyan
      - name: log the process
        run: echo checkout the code successfully !

