name: Blood pressure build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: checkout the code
        run: echo checkout the code successfully !
        with:
          first_name: Adithyan
