name: Blood pressure build
run-name: ${{github.actor}} is running the continuous integration

on:
  push:
    branches: [main]

jobs:
  build:
    name: bp build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is triggered by ${{github.event_name}} event".

      - name: checking out the code
        uses: actions/checkout@v5

      - name: list the code checkedout
        run: |
          ls ${{github.workspace}}


      - name: setup java and build project
        uses: actions/setup-java@v4
        with:
          java-version: 17
          cache: maven
          distribution: temurin

      - name: Build with maven
        run: mvn clean package

      - name: copy artificat into release folder
        run: mkdir release && cp target/*.jar release

      - name: upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: release

      - name: start the project
        run: java -jar /release/bloodpressure-0.0.1-SNAPSHOT.jar

      - name: Job status
        run: echo "The job is ${{job.status}} !"



