name: Blood pressure build
run-name: ${{github.actor}} is running the continuous integration

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is triggered by ${{github.event_name}} event".
      - name: checking out the code
        uses: actions/checkout@v5

      - name: log the process
        run: |
          ls ${{github.workspace}}
      - run: echo "The job is ${{job.status}} successfully !"
        env:
          PROJECT_NAME: BloodPressure

